### ISSUE TITLE
Landfill fills a fair large area

### ISSUE THREAD

**Issue by jodokus31** [Factorio-Xander-Mod/Xander-Mod#12]
If Landfill is placed, it fills a larger area than usually. It's not like the normal landfill bug, that can fill up to 4 tiles. I think, it places 9 or 16 tiles, if I place 1 landfill.

**Comment by lossycrypt** [comment]
Factorio tile autocorrection logic enforces that there must be grass tiles between any non-grass tiles and any water tile. So becaues landfill in xanders places gravel instead of grass autocorrect kicks in and places a two-wide border of grass tiles around it, for a total of 5x5 "land" tiles if placed in the middle of water.
No clue how to fix that though. Changing the layer of the gravel tile prototype might work, but that's only a wild guess (grass has layer = 20, gravel has layer = 37).

**Comment by lossycrypt** [comment]
Addendum:
Randomly stumbled over a mod called "water-fix" which supposedly deals with this kind of issue. Might be worth looking at their code. https://mods.factorio.com/mods/Earendel/water-fix

**Comment by jodokus31** [comment]
This mod definitly helps to place no grass around and tile by tile.
I looked it the code and it sets:
`data.raw.tile.water.allowed_neighbors = nil -- any`

There is also the mod landfill painting, which does something similar

```
if data.raw.tile['water'].allowed_neighbors then -- Other mods may remove this altogether
    table.insert(data.raw.tile['water'].allowed_neighbors, v)
end
```
where v is the tilename

**Comment by lossycrypt** [comment]
![notile](https://user-images.githubusercontent.com/14168854/33054593-75aa171e-ce7a-11e7-9532-ed81cc143ab7.png)
Interesting to know. Does require proper tile variations apparently though or else it'll look shitty. This is from base worldgen btw, so just setting it to "nil" looks like a bad idea if you don't want to supply variations for all possible tile combinations of every tile ever added :D

**Comment by Repofme1** [comment]
Aha, _that's_ how the base game tile logic works - it wants there to be grass between water and everything else!  I was also informed by someone on the forums of a similar issue, where some normal XM tiles can generate grass over water, so they act kind of like bootleg landfill.  Their example was steel plate, but concrete, basalt, fused quartz, or anything else I made placeable directly up to water does it.  I realized that this was the problematic feature, and it's a bug in the base game, so I don't really know what to do about it.

My reasoning for the tiles is mostly aesthetic.  The landfill places gravel for a more industrial feel, and you can sort of see where the original coastline was unless you pave it or cover everything with gravel.  The strong tiles like quartz, basalt, and steel can be placed right up to water because I like the option of making bulkhead-like structures, where a wall of constructed material drops vertically into the water.

**Comment by lossycrypt** [comment]
To prevent the "bootleg landfill" property of placable tiles you currently have to keep the condition size large enough. I tested with concrete and <place_as_tile.condition_size = 2>  looks almost like = 1 but properly prevents landfilling.

According to this bugreport: https://forums.factorio.com/viewtopic.php?f=213&t=54122 we can hope for 0.16 to fix this though.

**Comment by Repofme1** [comment]
And indeed, Factorio 0.16 does fix it!  Now we can have all the pavement placed directly adjacent to water without a problem, and landfill works on only the tiles it shows.
