### ISSUE TITLE
[1.4.1] Graphite powder incorrect recipe

### ISSUE THREAD

**Issue by Houkime** [Factorio-Xander-Mod/Xander-Mod#22]
It takes Granitic ore and water instead of taking anything carbon-related.
Doesn't sound like a legit industrial tech.
It wasn't so in previous versions of XM. Was introduced in 1.4.0

Edit: 
Just in case rechecked IRL minerals' compositions and ways to obtain carbon. Still doesn't make sense.

**Comment by Repofme1** [comment]
I made this change in 1.4.0 as part of looking at the whole graphite system.  I was trying to find how graphite was first discovered and produced, and initially it was actually mined.  It occurs in some metamorphic and igneous rocks, but I couldn't think of a good source ore for it in XM, so I just threw it in granitic ore.  I know that granite is not one of the rocks that can really have graphite, but I don't really know if any of the XM ores represent rocks that can contain graphite.
[https://en.wikipedia.org/wiki/Graphite](url)

I wanted to move it off of coke because if you stuck coke in a furnace it would just burn, and if you blocked out the air (as is done with coal to make coke) I think it would just sit there.  I believe that last point to be the case because large graphite electrodes for steelmaking are first heated to nearly 3000 C in order to make sure they are fully graphite (and not a disordered structure of carbon), but the early Factorio furnaces don't get anywhere near that hot.  A short random article I found that makes sense to me:
[http://www.graphiteconcept.com/content/view/33/27/](url)
